clean junk files and bug fixes

diff --git a/scripts/media/aniwatch b/scripts/media/aniwatch
--- a/scripts/media/aniwatch
+++ b/scripts/media/aniwatch
@@ -34,9 +34,9 @@ if [[ -z $1 ]] || [[ "$1" == "--download" ]] || [[ $1 == "--hide-subs" ]] || [[ 
 
     [ -z "$Select" ] && echo "nothing selected." && exit
 
-    currentEP=$(grep "$Select" $myFILE | cut -d '|' -f 2)
+    currentEP=$(grep "$Select" $myFILE |head -n1| cut -d '|' -f 2)
     EP=`expr "$currentEP" + 1 `
-    myChoice=$(grep "$Select" $myFILE | cut -d '|' -f 3)
+    myChoice=$(grep "$Select" $myFILE |head -n1| cut -d '|' -f 3)
 
     if [[ $1 == "--hide-subs" ]]; then
 	    if [[ ! -f /bin/screenkey ]] ; then
@@ -100,7 +100,9 @@ else
 	}
 	anime_name=$(animeName "$1")
 
-	if [[ -z $(grep "$anime_name" $myFILE) ]]; then
+	if [[ $(grep "$anime_name" $myFILE | cut -d '|' -f1 | head -n1 ) == $anime_name ]]; then
+	echo "$anime_name is Already in List!" ; exit
+	else
     	if [[ -z $3 ]]; then
         [ -z "$2" ] && echo "$anime_name|0|0|Watching" >> "$myFILE"\
             || echo "$anime_name|"$2"|0|Watching" >> "$myFILE"\
@@ -110,8 +112,6 @@ else
             || echo "$anime_name|"$2"|0|"$3"" >> "$myFILE"\
             && echo "Added $anime_name to Watchlist!"
     	fi
-	else
-	echo "$anime_name is Already in List!" ; exit
 	fi fi fi
 }
 
@@ -190,6 +190,17 @@ ueberzug_preview(){
    )
 }
 
+# [ Cleaning up if script got canceled while running ]
+__cleanup(){
+	rm urls 2>/dev/null
+	rm raw.txt 2>/dev/null
+	rm page.txt 2>/dev/null
+	rm pics 2>/dev/null
+	rm cover.png 2>/dev/null
+}
+
+trap __cleanup EXIT
+
 # [ the info flag ]
 myanimelist(){
 	 if [[ -z "$2" ]]; then
@@ -213,7 +224,7 @@ myanimelist(){
 
     myWord="$(cat page.txt | grep 'Synopsis' -A 2 | tail -n1 | cut -d ' ' -f 1-6)"
 
-    # cover photo
+    # download the cover photo
     myType=$(grep "Type:" page.txt | cut -d '[' -f 2 | cut -d ']' -f 1)
 
     if [[ $myType == "Manga" ]]; then
@@ -252,7 +263,7 @@ myanimelist(){
     grep -F '## Reviews' -A 400 raw.txt | grep -v '^|' | grep -Fv '[' | grep -Fv ']' | sed -e '/^Sort/,+7d' | cat -s | fold -w `expr $(echo $COLUMNS) - 30`
     echo -e "$(tput setaf 2)---------------------------------------"
 
-# [ Final Look ]
+# [ The Final Look ]
     ) | bat --file-name "$Title" & ueberzug_preview cover.png & sleep 5 && while true; do ! pgrep -x bat > /dev/null && killall ueberzug &&\
     rm page.txt &&\
     rm raw.txt &&\
@@ -261,8 +272,17 @@ myanimelist(){
     exit; done
 }
 
+# [ cleaning up ]
+__cleanup2(){
+	rm html 2>/dev/null
+	rm urls 2>/dev/null
+}
+
+trap __cleanup2 EXIT
+
 # [ --export flag ]
 export_my_list(){
+	# [ User Info ]
 	myFILE="$XDG_CACHE_HOME/watchlist"
 	lines_num=$(cat $myFILE | wc -l )
 	info=0
@@ -284,7 +304,8 @@ export_my_list(){
 					<user_total_plantowatch>$(grep -i plan $myFILE|wc -l)</user_total_plantowatch>
 				</myinfo>
 	" >> exported_list.xml
-	echo "Please be patient, this will take a few minutes."
+	echo "Please be patient, this can take a few minutes."
+	# [ Anime info loop ]
 	for info in $(seq 1 $lines_num); do
 		echo "Exporting $name Info!"
 		info=$(($info+1))
@@ -334,6 +355,7 @@ export_my_list(){
 	echo "Exported $lines_num Shows."
 }
 
+# [ importing from xml file ]
 import_my_list(){
     if [[ $2 == *.gz ]]; then
         my_xml_list=$(echo "$2" | sed 's/.gz//g' )
@@ -347,6 +369,7 @@ import_my_list(){
 
     }
 
+# [ General help message ]
 help_message(){
     MOVE_UP=`tput cuu 1` ; CLEAR_LINE=`tput el 1` ; BOLD=`tput bold` ; UNDERLINE=`tput smul` ; RESET=`tput sgr0`
 
@@ -385,6 +408,7 @@ help_message(){
         "
 }
 
+# [ some of the flags in case format ]
 case "$1" in
     -e | --edit ) vim "$myFILE" ; exit ;;
     -l | --list ) my_list ; exit ;;
